app:
  name: inventory-app-test

# for stock level
demandTypes: HARD_PROMISED
supplyTypes: ONHAND
locations:
  exclude: '18100'

# spring
spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/db_inventory_app"


# logging
logging:
  file:
    name: app.log
  level:
    com:
      mdsujan:
        restPostgres:
          controller: trace

# for app's local running
server:
  port: '8088'
  error:
    include-message: always

