app:
  name: inventory-app-default

# for stock level
demandTypes: HARD_PROMISED
supplyTypes: ONHAND
locations:
  exclude: '18100'

# spring
spring:
  jpa:
    database: mongodb
    show-sql: 'true'
    show-jpql: 'true'
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: inventory_app
      port: 27017
      host: localhost
  cache:
    redis:
      time-to-live: 10S
# logging
logging:
  file:
    name: app.log
  level:
    com:
      mdsujan:
        restPostgres:
          controller: trace

# for app's local running
server:
  port: '8088'
  error:
    include-message: always


